import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./styles/globals.css";

// Components
import Nav from "./comp/Nav";
import Footer from "./comp/Footer";

// Fonts
import { Rubik, Inria_Sans, Inter } from "next/font/google";
const rubik = Rubik({ subsets: ["latin"] });
const inria = Inria_Sans({
  subsets: ["latin"],
  weight: "300",
});

// Object Literal
export const metadata: Metadata = {
  title: "orjacksoniv.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
